server:
  port: 8080

spring:
  application:
    name: products-service
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        jdbc:
#         lob:
#            non_contextual_creation: true
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: admin


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

