server:
  port: 8082

spring:
  application:
    name: orders-feign-client
  data:
    mongodb:
      database: test_db
      port: 27017
      host: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


